apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: haproxy-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        ports:
        - containerPort: 8000
          name: http














