apiVersion: v1
kind: Service
metadata:
  name: leagues-web-service
spec:
  ports:
    - port: 4002
      targetPort: 4001
      protocol: TCP
      name: http
  selector:
    app: leagues-web
  type: LoadBalancer
