# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090
  access: proxy
  